### PR TITLE
Feat/3164 megre existing commit hook repos

### PR DESCRIPTION
**Pull request by mukesh-flux7**
Moved the hooks shell scripts from the pre-commit repo into this repo central-repo-git-hooks, and I have also added the .github dir with the Flux7 PR Template.

### CODE REVIEW

**Review by hanumantharaomvl — APPROVED** [review]

**Review by deric4 — CHANGES_REQUESTED** [review]
@mukesh-flux7 were the files add in the .github dir added by the `git subtree` command?

I don't see any git logs that indicate that.

**Comment by deric4** [comment]
[T Test hooks Part 1](https://trello.com/c/ADSsSipL/3165-t-test-hooks-part-1)

Verification that hooks execute 

**Validate Email** Hooks has a bug where its receiving the list of files to be checked so it doesn't use default value.

```


[WARNING] Creating temporary repo with uncommitted changes...
[INFO] Initializing environment for /var/folders/9q/2vvhgyjx7_d1cqy24mgqx8yc0000gn/T/tmpfkn3oko4/shadow-repo.
===============================================================================
Using config:
===============================================================================
repos:
-   repo: /var/folders/9q/2vvhgyjx7_d1cqy24mgqx8yc0000gn/T/tmpfkn3oko4/shadow-repo
    rev: 5a8468550a7c8c8e3309ab7bf4316c3ad6c5833a
    hooks:
    -   id: cfn-lint
    -   id: check-readme
    -   id: packer-validate
    -   id: terraform-fmt
    -   id: validate-author-email
    -   id: validate-author-email
===============================================================================
Cloudformation Lint......................................................Failed
- hook id: cfn-lint
- duration: 0.02s
- exit code: 1

+ CF_CHECK=AWSTemplateFormatVersion
+ templates=($(git diff --diff-filter=d --name-only --cached -- '*.yaml' | xargs grep -l $CF_CHECK))
++ git diff --diff-filter=d --name-only --cached -- '*.yaml'
++ xargs grep -l AWSTemplateFormatVersion

Check for readme file....................................................Passed
- hook id: check-readme
- duration: 0.01s
Packer validate..........................................................Passed
- hook id: packer-validate
- duration: 0.01s
Terraform fmt............................................................Passed
- hook id: terraform-fmt
- duration: 0.08s
Validate the author flux7 email address..................................Failed
- hook id: validate-author-email
- duration: 0.01s
- exit code: 1

++ git config user.email
+ AUTHOR_EMAIL=deric@flux7.com
+ DOMAIN=cf-test-template.yaml
+ [[ cf-test-template.yaml = '' ]]
+ [[ deric@flux7.com == *\c\f\-\t\e\s\t\-\t\e\m\p\l\a\t\e\.\y\a\m\l* ]]
+ echo '######################################################'
######################################################
+ echo 'Author email configured is not a flux7 email'
Author email configured is not a flux7 email
+ echo ' run:'
 run:
+ echo '     git config user.email "****@flux7.com"'
     git config user.email "****@flux7.com"
+ echo or
or
+ echo '     git config --global user.email "*****@flux7.com"'
     git config --global user.email "*****@flux7.com"
+ echo 'Then try commiting again'
Then try commiting again
+ echo '######################################################'
######################################################
+ exit 1

Validate the author flux7 email address..................................Failed
- hook id: validate-author-email
- duration: 0.01s
- exit code: 1

++ git config user.email
+ AUTHOR_EMAIL=deric@flux7.com
+ DOMAIN=cf-test-template.yaml
+ [[ cf-test-template.yaml = '' ]]
+ [[ deric@flux7.com == *\c\f\-\t\e\s\t\-\t\e\m\p\l\a\t\e\.\y\a\m\l* ]]
+ echo '######################################################'
######################################################
+ echo 'Author email configured is not a flux7 email'
Author email configured is not a flux7 email
+ echo ' run:'
 run:
+ echo '     git config user.email "****@flux7.com"'
     git config user.email "****@flux7.com"
+ echo or
or
+ echo '     git config --global user.email "*****@flux7.com"'
     git config --global user.email "*****@flux7.com"
+ echo 'Then try commiting again'
Then try commiting again
+ echo '######################################################'
######################################################
+ exit 1

```

**Comment by mukesh-flux7** [comment]
> @mukesh-flux7 were the files add in the .github dir added by the `git subtree` command?
> 
> I don't see any git logs that indicate that.

I have added the PR template with the git subtree command now .https://github.com/Flux7Labs/central-repo-git-hooks/commit/d8982acaa11845f1a41e2375e9b44d8a72703783

**Review by deric4 — APPROVED** [review]

**Comment by deric4** [comment]
LGTM

**Review by KishorFlux7 — APPROVED** [review]
LGTM

**Pull request merged**
