### PR TITLE
Support for Code-Linter concurrent builds.

### PR DESCRIPTION
**Pull request by hanumantharaomvl**
Task Link: https://trello.com/c/AnZAsLZr

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Developer Checklist
- [ ] My change requires a change to the documentation.
- [x] I have updated my branch with the latest changes in master.
- [ ] I have communicated with the team any changes that might affect work in progress. 
- [x] I have updated Trello to reflect current state of the feature. 

## Documentation Checklist
- [ ] I have updated the necessary README's
- [ ] I have updated the Runbook

## Description of Changes
Observed pre-commit clean is cleaning-up the hooks scripts which is causing other concurrent jobs fail. Removing cleanup commands to support concurrent builds.

## Description of Testing Process

Updated the branch name and triggered 5 jobs at the same time to validate and all the builds were able to find the hook scripts and issue is not observed.

```
https://internal-commo-jenki-dnef72g28tsg-407778437.us-east-1.elb.amazonaws.com/job/Code-Linter/1172/console
https://internal-commo-jenki-dnef72g28tsg-407778437.us-east-1.elb.amazonaws.com/job/Code-Linter/1171/console
https://internal-commo-jenki-dnef72g28tsg-407778437.us-east-1.elb.amazonaws.com/job/Code-Linter/1170/console
https://internal-commo-jenki-dnef72g28tsg-407778437.us-east-1.elb.amazonaws.com/job/Code-Linter/1169/console
https://internal-commo-jenki-dnef72g28tsg-407778437.us-east-1.elb.amazonaws.com/job/Code-Linter/1168/console
```

### CODE REVIEW

**Comment by shadycuz** [comment]
Jenkins's workspace is supposed to allow concurrent builds. https://stackoverflow.com/questions/45196297/jenkins-workspaces-and-concurrent-builds-how-do-they-work

I personally have kicked off multiple jobs like terraform at the same time with 0 problems. Perhaps the root cause is related but something different?

**Comment by hanumantharaomvl** [comment]
> Jenkins's workspace is supposed to allow concurrent builds. https://stackoverflow.com/questions/45196297/jenkins-workspaces-and-concurrent-builds-how-do-they-work
> 
> I personally have kicked off multiple jobs like terraform at the same time with 0 problems. Perhaps the root cause is related but something different?

Hi @shadycuz ,

```
pre-commit clean
Cleaned /var/lib/jenkins/.cache/pre-commit.
```

The jobs were already using unique workspace during the concurrent builds, but the issue is with the pre-commit clean. pre-commit by default places its repository store in ~/.cache/pre-commit and during the clean command its cleaning up the existing hooks scripts causing the other jobs fail. We either include the HOMEDIR for pre-commit or take out the clean-up command, i opted for the second one as we dont change the hooks scripts that often so there will not be frequent updates to the hook scripts.

workspaces for concurrent jobs,
```
Running pre-commit hook validation using /var/lib/jenkins/workspace/Code-Linter/central-repo-git-hooks/.pre-commit-pr-
hooks.yaml...
Running pre-commit hook validation using /var/lib/jenkins/workspace/Code-Linter@2/central-repo-git-hooks/.pre-commit-pr-
hooks.yaml...
```

**Comment by shadycuz** [comment]
@hanumantharaomvl Is it possible to set the homedir for pre-commit to the workdir? 

I ask because this fix only fixed this job. Their could be other jobs now or in the future that try to run pre-commit concurrently and has the same issue?

**Comment by hanumantharaomvl** [comment]
> @hanumantharaomvl Is it possible to set the homedir for pre-commit to the workdir?
> 
> I ask because this fix only fixed this job. Their could be other jobs now or in the future that try to run pre-commit concurrently and has the same issue?

Sure @shadycuz , let me validate that.

**Comment by hanumantharaomvl** [comment]
> > @hanumantharaomvl Is it possible to set the homedir for pre-commit to the workdir?
> > I ask because this fix only fixed this job. Their could be other jobs now or in the future that try to run pre-commit concurrently and has the same issue?
> 
> Sure @shadycuz , let me validate that.

@shadycuz , I have validated the jenkins job with set the cache to workspace dir and validated. That does not need change to this repo, created another PR from jobs repo. https://github.com/Flux7Labs/template-repo-jenkins-jobs/pull/340

**Pull request closed without merging**
