### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by philipakash**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation change
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Developer Checklist
- [ ] My change requires a change to the documentation.
- [x] I have updated my branch with the latest changes in master.
- [ ] I have communicated with the team any changes that might affect work in progress. 
- [x] I have updated Trello to reflect current state of the feature. 

## Documentation Checklist
- [ ] I have updated the necessary README's
- [ ] I have updated the Runbook

## Description of Changes

Adding License file

## Context

NA

## Description of Testing Process

NA

### CODE REVIEW

**Comment by hanumantharaomvl** [comment]
@philipakash I see we had license file in md format. ex, https://github.com/Flux7Labs/ansible-role-configure-jenkins/blob/master/LICENSE.md do we need to maintain the same file format ?

**Comment by philipakash** [comment]
sure @hanumantharaomvl Let me change it to MD

**Review by hanumantharaomvl — APPROVED** [review]
👍

**Review by agaur123 — APPROVED** [review]
:shipit:

**Pull request merged**
