### PR TITLE
Upgrading PIP to automatically resolve dependency issues.

### PR DESCRIPTION
**Pull request by hanumantharaomvl**
Task Link: https://trello.com/c/jGoSkK7F

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation change
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Developer Checklist
- [ ] My change requires a change to the documentation.
- [x] I have updated my branch with the latest changes in master.
- [ ] I have communicated with the team any changes that might affect work in progress. 
- [x] I have updated Trello to reflect current state of the feature. 

## Documentation Checklist
- [ ] I have updated the necessary README's
- [ ] I have updated the Runbook

## Description of Changes
Upgrading PIP to automatically resolve dependencies. Upgraded PIP is coming with dependency resolver as default which will update the pkgs to the versions compatible.

## Context
Observed the linting checks are failing due to pip package version conflicts.

## Description of Testing Process
Tested Locally.

### CODE REVIEW

**Review by sirhc — CHANGES_REQUESTED** [review]
@hanumantharaomvl: Can you provide more context in this PR? Perhaps an example of the failure and why this fixes it?

I looked at the individual commits, but they were not explanatory, either.

**Comment by hanumantharaomvl** [comment]
> @hanumantharaomvl: Can you provide more context in this PR? Perhaps an example of the failure and why this fixes it?
> 
> I looked at the individual commits, but they were not explanatory, either.

Hi @sirhc I have already added the comments in the PR template.

Errors observed during the dca infra code build process, The existing pip version is complaning about dependency version conflicts though they are not pinned. 

```

2021-03-18T23:14:07.510+05:30 | ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
-- | --
  | 2021-03-18T23:14:07.510+05:30 |  
  | 2021-03-18T23:14:07.510+05:30 | We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
  | 2021-03-18T23:14:07.510+05:30 |  
  | 2021-03-18T23:14:07.510+05:30 | cookiecutter 1.7.2 requires requests>=2.23.0, but you'll have requests 2.22.0 which is incompatible.
  | 2021-03-18T23:14:07.510+05:30 | awscli 1.19.18 requires botocore==1.20.18, but you'll have botocore 1.15.49 which is incompatible.
  | 2021-03-18T23:14:07.510+05:30 | aws-sam-cli 1.19.1 requires boto3~=1.14, but you'll have boto3 1.12.43 which is incompatible.
  | 2021-03-18T23:14:07.510+05:30Copyaws-sam-cli 1.19.1 requires requests==2.23.0, but you'll have requests 2.22.0 which is incompatible. | aws-sam-cli 1.19.1 requires requests==2.23.0, but you'll have requests 2.22.0 which is incompatible.
  | 2021-03-18T23:14:07.510+05:30 | bc-python-hcl2 0.3.18 requires lark-parser<0.11.0,>=0.10.0, but you'll have lark-parser 0.7.8 which is incompatible.
  | 2021-03-18T23:14:07.510+05:30 | checkov 1.0.580 requires junit-xml==1.8, but you'll have junit-xml 1.9 which is incompatible.
  | 2021-03-18T23:14:07.510+05:30 | Successfully installed GitPython-3.1.7 bc-python-hcl2-0.3.18 boto3-1.12.43 botocore-1.15.49 cfgv-3.2.0 cfn-lint-0.47.2 checkov-1.0.580 decorator-4.4.2 docopt-0.6.2 dpath-1.5.0 flake8-3.9.0 gitdb-4.0.5 identify-2.1.3 idna-2.8 jsonpatch-1.32 jsonpointer-2.1 junit-xml-1.9 lark-parser-0.7.8 mccabe-0.6.1 networkx-2.5 nodeenv-1.5.0 pre-commit-2.11.1 pycodestyle-2.7.0 pyflakes-2.3.0 requests-2.22.0 smmap-3.0.5 tabulate-0.8.6 termcolor-1.1.0 toml-0.10.2 tqdm-4.49.0 urllib3-1.25.10
  | 2021-03-18T23:14:07.510+05:30 | WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
  | 2021-03-18T23:14:07.510+05:30 | You should consider upgrading via the '/root/.pyenv/versions/3.8.8/bin/python3.8 -m pip install --upgrade pip' command.
```

After upgrading the PIP locally, it was able to update the package versions which were not pinned to the compatible versions.
For ex, Upgraded pip uninstalled the uncompatible version and installed the compatible version 1.8.
```
checkov 1.0.580 requires junit-xml==1.8, but you'll have junit-xml 1.9 which is incompatible.
```

```
  Attempting uninstall: junit-xml
    Found existing installation: junit-xml 1.9
    Uninstalling junit-xml-1.9:
      Successfully uninstalled junit-xml-1.9
```

**Review by sirhc — APPROVED** [review]
Thank you for the explanation, @hanumantharaomvl. It makes perfect sense to me now.

**Comment by hanumantharaomvl** [comment]
> Thank you for the explanation, @hanumantharaomvl. It makes perfect sense to me now.

Seems its not fully automated, Its passing locally and need to check after the merge. 🤞 

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
```

**Pull request merged**
